### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by si1meria** [si1meria/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

**Comment by si1meria** [comment]
これから対応します。

**Comment by s1lmer1a** [comment]
81989ad で対応さました。

**Comment by si1meria** [comment]
81989ad で対応されました。
